steps:
  - name: node:24.0.1
    entrypoint: npm
    args: ["install"]
  - name: node:24.0.1
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 3600 && gcloud app deploy dev_app.yaml",
      ]
timeout: "3600s"
options:
  machineType: "E2_HIGHCPU_32"
